# Generated by Django 4.2.2 on 2023-07-10 01:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("web", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="employee",
            name="profile_photo",
            field=models.CharField(default=1, max_length=200, verbose_name="头像路径"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="oldperson",
            name="profile_photo",
            field=models.CharField(default=1, max_length=200, verbose_name="头像路径"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="volunteer",
            name="profile_photo",
            field=models.CharField(default=1, max_length=200, verbose_name="头像路径"),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="employee",
            name="age",
            field=models.IntegerField(blank=True, verbose_name="年龄"),
        ),
        migrations.AlterField(
            model_name="employee",
            name="checkin_date",
            field=models.DateTimeField(blank=True, verbose_name="入职日期"),
        ),
        migrations.AlterField(
            model_name="employee",
            name="gender",
            field=models.CharField(blank=True, max_length=5, verbose_name="性别"),
        ),
        migrations.AlterField(
            model_name="employee",
            name="phone",
            field=models.CharField(blank=True, max_length=50, verbose_name="电话"),
        ),
        migrations.AlterField(
            model_name="event",
            name="event_date",
            field=models.DateTimeField(blank=True, verbose_name="事件发送日期"),
        ),
        migrations.AlterField(
            model_name="oldperson",
            name="age",
            field=models.IntegerField(blank=True, verbose_name="年龄"),
        ),
        migrations.AlterField(
            model_name="oldperson",
            name="checkin_date",
            field=models.DateTimeField(blank=True, verbose_name="入院日期"),
        ),
        migrations.AlterField(
            model_name="oldperson",
            name="guardian_name",
            field=models.CharField(blank=True, max_length=50, verbose_name="监护人姓名"),
        ),
        migrations.AlterField(
            model_name="oldperson",
            name="health_state",
            field=models.CharField(blank=True, max_length=50, verbose_name="健康状况"),
        ),
        migrations.AlterField(
            model_name="oldperson",
            name="phone",
            field=models.CharField(blank=True, max_length=50, verbose_name="电话"),
        ),
        migrations.AlterField(
            model_name="sysuser",
            name="email",
            field=models.CharField(blank=True, max_length=50, verbose_name="邮箱"),
        ),
        migrations.AlterField(
            model_name="sysuser",
            name="gender",
            field=models.CharField(blank=True, max_length=5, verbose_name="性别"),
        ),
        migrations.AlterField(
            model_name="sysuser",
            name="phone",
            field=models.CharField(blank=True, max_length=50, verbose_name="电话"),
        ),
        migrations.AlterField(
            model_name="volunteer",
            name="age",
            field=models.IntegerField(blank=True, verbose_name="年龄"),
        ),
        migrations.AlterField(
            model_name="volunteer",
            name="checkin_date",
            field=models.DateTimeField(blank=True, verbose_name="访问日期"),
        ),
        migrations.AlterField(
            model_name="volunteer",
            name="gender",
            field=models.CharField(blank=True, max_length=5, verbose_name="性别"),
        ),
        migrations.AlterField(
            model_name="volunteer",
            name="phone",
            field=models.CharField(blank=True, max_length=50, verbose_name="电话"),
        ),
    ]
