# Generated by Django 4.2.2 on 2023-07-10 02:02

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("web", "0002_employee_profile_photo_oldperson_profile_photo_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="employee",
            name="profile_photo",
        ),
        migrations.RemoveField(
            model_name="oldperson",
            name="profile_photo",
        ),
        migrations.RemoveField(
            model_name="volunteer",
            name="profile_photo",
        ),
    ]
